---
title: "Preprocess_OF - EMO VALENCE STUDY"
author: "Helio"
date: "2023-02-27"
output: html_document
---


```{r setup, include=FALSE}

install.packages("tidyverse")

require(tidyverse)
# Set working directory to the folder containing subfolders with CSV files
setwd("~/Library/CloudStorage/GoogleDrive-helioclemente.c@gmail.com/My Drive/University of Oxford/Students/StephaniesProject/Data/OpenFace1")

setwd("~/Library/CloudStorage/GoogleDrive-helioclemente.c@gmail.com/My Drive/University of Oxford/Students/StephaniesProject/Data/OpenFace1")

# Get a list of all CSV files within subfolders using list.files() and recursive = TRUE
tmp_file_list <- list.files(pattern = "\\.csv$", recursive = TRUE, full.names = TRUE)
unique(substr(tmp_file_list,1,16))

# Initialize an empty data frame to hold combined data
dta_combined_OF <- data.frame()

# Loop through each CSV file in the list and read it into a data frame using read.csv()

# read the CSV files into a list of data frames, and store the filename as a new column in each data frame
tmp_data_list <- lapply(tmp_file_list, function(file) {
  data <- read.csv(file)
  data$filename <- file
  data
})

# combine the data frames into a single data frame

dta_combined_OF <- do.call(rbind, tmp_data_list)

rm(tmp_data_list)


saveRDS(dta_combined_OF, "dta_combined_OF_newmac_compressed.Rds")
# View the resulting combined data frame
dta_combined_OF

unique(dta_combined_OF$filename)

# write_rds(dta_combined_OF, "dta_combined_OF,rds")

length(colnames(dta_combined_OF))

dta_OF_combined_select<- dta_combined_OF[,c(1:5, 680:715)]

rm(dta_combined_OF)

colnames(dta_OF_combined_select)
rm(tmp_file_list)
# create variables

dta_OF_combined_select$filename
dta_OF_combined_select

library(stringi)
library(stringr)
dta_OF_combined_select$ssid <- str_remove_all(substr(dta_OF_combined_select$filename, 2,16),"/")


unique(dta_OF_combined_select$ssid)


# practice
library(tidyverse)


# the first 8 fumbers after the second slash are task code and version
# df$substring <- str_extract(df$url, "(?<=//[^/]+/[^/]+/).{5}")
# return evrything after the second slash then keep the first 8 


dta_OF_combined_select$task_code_v <- substr(sub("^([^/]+/[^/]+/)(.*)", "\\2", dta_OF_combined_select$filename), 1,8)
unique(dta_OF_combined_select$task_code_v )

# participant private id
# unique(substr(sub("^([^/]+/[^/]+/)(.*)", "\\2", dta_OF_combined_select$filename), 10,10+7))
dta_OF_combined_select$participant_private_id<- substr(sub("^([^/]+/[^/]+/)(.*)", "\\2", dta_OF_combined_select$filename), 10,10+6)
unique(dta_OF_combined_select$participant_private_id)

# dta_OF_combined_select$trial_number<- 
# 
# length(unique(dta_OF_combined_select$participant_private_id))



library(stringr)


dta_OF_combined_select$stimIAPS<- paste0(str_extract(dta_OF_combined_select$filename, "(.{4})(?=\\jpg)"),".jpg")
unique(dta_OF_combined_select$stimIAPS)

# get number

# after that pattern
# df$suffix <- sub(".*(.jpg)", "\\1", df$filename)
dta_OF_combined_select$filename_digits_aftjpg<- 
  str_remove_all(substr(str_remove_all(sub(".*(jpg)", "\\1", dta_OF_combined_select$filename),"jpg-"),1,2),"-")

dta_OF_combined_select$trial_number<-
dta_OF_combined_select$filename_digits_aftjpg
unique(dta_OF_combined_select$trial_number)
 

dta_OF_combined_select$filename_digits_bef_csv<- str_remove_all(sub(".*(-)", "\\1", str_remove_all(sub(".*(jpg)", "\\1", dta_OF_combined_select$filename),"jpg-")), "-|.csv")

dta_OF_combined_select$practice_trial<- if_else(dta_OF_combined_select$filename_digits_bef_csv == "1", "practice", "trial")


dta_OF_combined_select$practice_trial
dta_OF_combined_select$practice_trial_no<- if_else(dta_OF_combined_select$practice_trial == "trial",2,1)

colnames(dta_OF_combined_select)



```

aggregate
```{r}

colnames(dta_OF_combined_select)

# summarise 
# require(tidyverse)

dta_OF_combined_select_agg <- dta_OF_combined_select%>%
  group_by(ssid, practice_trial,stimIAPS,task_code_v,participant_private_id,trial_number)%>%
  summarise_if(is.numeric, mean, na.rm = T)

colnames(as.data.frame(dta_OF_combined_select_agg))


tmp_AUnames

# new names with AU descriptions
tmp_AUnames<- c("ssid" ,         
                "practice_trial", 
                "stimIAPS"   ,   
                "task_code_v",
                 "participant_private_id",
                "trial_number",
                "frame"    ,     
                "face_id"      , 
                "timestamp"   ,  
                "confidence" ,   
                "success",
 "AU01_r_Inner_brow_raiser",   
 "AU02_r_Outer_brow_raiser",   
 "AU04_r_Brow_lowerer",       
"AU05_r_Upper_lid_raiser",    
"AU06_r_Cheek_raiser",        
"AU07_r_Lid_tightener",       
"AU09_r_Nose_wrinkler",      
 "AU10_r_Upper_lip_raiser",    
"AU12_r_Lip_corner_puller",   
"AU14_r_Dimpler",             
"AU15_r_Lip_corner_depressor",
 "AU17_r_Chin_raiser",         
"AU20_r_Lip_stretcher",       
"AU23_r_Lip_tightener",      
"AU25_r_Lips_part",          
"AU26_r_Jaw_drop",            
"AU45_r_Blink",               
"AU01_c_Inner_brow_raiser",   
"AU02_c_Outer_brow_raiser",  
"AU04_c_Brow_lowerer",        
"AU05_c_Upper_lid_raiser",    
"AU06_c_Cheek_raiser",        
"AU07_c_Lid_tightener",      
"AU09_c_Nose_wrinkler",      
"AU10_c_Upper_lip_raiser",    
"AU12_c_Lip_corner_puller",   
"AU14_c_Dimpler",            
 "AU15_c_Lip_corner_depressor",
"AU17_c_Chin_raiser",        
"AU20_c_Lip_stretcher",       
"AU23_c_Lip_tightener",      
"AU25_c_Lips_part",          
"AU26_c_Jaw_drop",    
"AU28_c_Lip_suck",    
"AU45_c_Blink","practice_trial_no")
tmp_AUnames

# dta_OF_combined_select_stimuli_agg2<- dta_OF_combined_select_stimuli_agg
colnames(dta_OF_combined_select_agg)<- tmp_AUnames
colnames(dta_OF_combined_select_agg)

dta_OF_combined_select_agg
write_csv(dta_OF_combined_select_agg, "dta_OF_combined_select_agg.csv")


```


